[package]
name = "crate"
version = "0.1.0"
authors = ["mizchi <miz404@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "^0.2"
js-sys = "^0.3.46"
rand = "0.6"
chrono = "0.4.19"
[dependencies.web-sys]
version = "0.3.46"

[lib]
crate-type = ["cdylib"]

